### ISSUE TITLE
Add setup.py 

### ISSUE THREAD

**Issue by taalexander** [SchusterLab/quantum-optimal-control#1]
Hello, 
Some members of the Cory group at IQC were thinking about implementing GRAPE on the GPU/Tensorflow to gain a speedup over our Mathematica implementation, which while having a nice interface and many complex-features is showing its age. We were thrilled to find your repository and hope to use, and contribute to it. 

I thought I would create the first issue on Github and suggest the creation of a setup.py file as per [PEP 229](https://www.python.org/dev/peps/pep-0229/), with [setuptools](http://setuptools.readthedocs.io/en/latest/setuptools.html). This way new users could easily install the library. In addition it would then be possible to change the initial path appends at the start of the examples in the [example repository](https://github.com/SchusterLab/GRAPE-Tensorflow-Examples).

If this is something you are interested in, I can put together a pull request with for this issue. 

Once again I would like to thank you for your work, I think it is something the community needs going into the future, and the automatic differentiation, and GPU capabilities of Tensorflow will be very powerful. 

Best Regards,
Thomas Alexander

**Comment by taalexander** [comment]
I also just wanted to add that we have several other suggestions/issues that I would raise if you are receptive. I just wanted to first introduce myself before doing so.

**Comment by nelsonleung** [comment]
We are glad to hear your interest in using and contributing to this repository! Adding a setup file sounds great and will definitely be useful to new users. You are welcome to put up a pull request or commit to our repository (sent you an invitation as our collaborators). We are more than happy to discuss further on the other suggestions/issues you have in mind.

**Comment by taalexander** [comment]
Hello Nelson,
That is great news. I will go ahead and submit a pull request for this once I've written it up. I will submit a couple other issues that have popped up, with pull requests incoming at a later date.

**Comment by taalexander** [comment]
Resolved with PR #6
