### ISSUE TITLE
Negative loss

### ISSUE THREAD

**Issue by pranavm1502** [SchusterLab/quantum-optimal-control#11]
I get a negative infidelity for L-BFGS-B algorithm. This should imply that there is something incorrect in the reg_loss or  inner_product_2D function. But I am unable to figure out the problem.

![image](https://user-images.githubusercontent.com/9042954/42973739-5d02a7ba-8b82-11e8-8234-0fc7e58dfc6f.png)

**Comment by nelsonleung** [comment]
Hi Pranav, 

From the plot I see your Unitary Metric tr(U^dag * U)/dim(U)[0] to be 1.00052 > 1. A non-1.0 Unitary Metric typically means your delta t is too large, which causes numerical instability. This can be solved by setting a larger number of step size. Let me know if it works for you.

**Comment by pranavm1502** [comment]
Hi Nelson,

Thanks for the advice! That works.
