### ISSUE TITLE
Module and Class Names 

### ISSUE THREAD

**Issue by taalexander** [SchusterLab/quantum-optimal-control#5]
As per [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) module names should be lowercase with multi-word names separated by underscores ie. `this_is_a_correct_module_name`. Many modules have class style naming such as `TensorflowState.py`. I believe that modules and classes should be renamed to agree with PEP 8, which will make code more consistent and readable.

**Comment by nelsonleung** [comment]
Thanks for pointing it out. I will update the module names.

**Comment by nelsonleung** [comment]
Module names updated in commit 245a22b8a55c1ed4728402c4a2987dcab229952d.
