### ISSUE TITLE
Unable to import after setup

### ISSUE THREAD

**Issue by pranavm1502** [SchusterLab/quantum-optimal-control#9]
Hi,

After cloning the repository, I ran `sudo python setup.py install`. It completed the setup, but I was unable to import the module. I am new to installing python packages from git. Any help will be appreciated.

Best,
Pranav

**Comment by geyang** [comment]
you shouldn't need to sudo python setup, b/c then it installs only for the
superuser's environment.

you can either try to run pip install -e . (installs locally by adding the
path to the python environment) (make sure you don't sudo). Or you can use
a conda environment.

Ge

**Comment by pranavm1502** [comment]
Thanks for the prompt response!  I was unable to install the package without using `sudo` . 

However, adding the cloned folder path to the sys.path seems to have worked.

**Comment by geyang** [comment]
Great!
btw there is likely something wrong if you can't do pip install without
sudo.

**Comment by pranavm1502** [comment]
I think it might be due to the way our high-performance computers are set up. I will look into it.

On a side note, I have found a small typo in the example notebooks. This was probably due to changing the module name for compliance with PEP8 (as mentioned in an earlier issue)

[Correction] - `from quantum_optimal_control.main_grape.Grape import Grape`  should be `from quantum_optimal_control.main_grape.grape import Grape`. If you think it's useful, I could send a pull request to https://github.com/SchusterLab/GRAPE-Tensorflow-Examples/tree/master after checking the examples for any other conflicts

**Comment by geyang** [comment]
@nleung91 @circuitqed see above

**Comment by nelsonleung** [comment]
@pranavm1502 I think you are right! Thanks for pointing it out.

**Comment by nelsonleung** [comment]
fixed b1889374b31ea45c8b27cabb971166c22b9c3c66
